{{- if .Values.server.registrationToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drawbar.fullname" . }}-registration
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  token: {{ .Values.server.registrationToken | quote }}
{{- end }}
